import { addPropertyControls, ControlType } from 'framer';
import { FlipCard } from './FlipCard';

export default FlipCard;

const labelTextOffsetControls = {
  x: {
    type: ControlType.Number as const,
    title: 'Horizontal',
    defaultValue: 0,
    min: -64,
    max: 64,
    step: 1,
    unit: 'px',
  },
  y: {
    type: ControlType.Number as const,
    title: 'Vertical',
    defaultValue: 0,
    min: -64,
    max: 64,
    step: 1,
    unit: 'px',
  },
};

const imageFocalControls = {
  x: {
    type: ControlType.Number as const,
    title: 'X',
    defaultValue: 0.5,
    min: 0,
    max: 1,
    step: 0.05,
  },
  y: {
    type: ControlType.Number as const,
    title: 'Y',
    defaultValue: 0.5,
    min: 0,
    max: 1,
    step: 0.05,
  },
};

addPropertyControls(FlipCard, {
  image: {
    type: ControlType.ResponsiveImage,
    title: 'Photo',
  },
  frontImageFocal: {
    type: ControlType.Object,
    title: 'Photo Position',
    controls: imageFocalControls,
  },
  frontImageZoom: {
    type: ControlType.Number,
    title: 'Photo Zoom',
    defaultValue: 1,
    min: 0.5,
    max: 2,
    step: 0.05,
  },
  title: {
    type: ControlType.String,
    title: 'Title',
    defaultValue: 'Jason Lee',
  },
  description: {
    type: ControlType.String,
    title: 'Description',
    defaultValue: 'Front-End Developer',
    displayTextArea: true,
    hidden: (props) => !props.showLabel,
  },
  showLabel: {
    type: ControlType.Boolean,
    title: 'Show Label',
    defaultValue: true,
  },
  showBackItems: {
    type: ControlType.Boolean,
    title: 'Show Back List',
    defaultValue: false,
  },
  backItems: {
    type: ControlType.Array,
    title: 'Back Items',
    control: {
      type: ControlType.String,
    },
    defaultValue: ['5+ years experience', 'React & TypeScript', 'Based in NYC'],
    hidden: (props) => !props.showBackItems,
  },
  badge: {
    type: ControlType.String,
    title: 'Badge',
  },
  showCta: {
    type: ControlType.Boolean,
    title: 'Show Button',
    defaultValue: true,
  },
  link: {
    type: ControlType.Link,
    title: 'Link',
    hidden: (props) => !props.showCta,
  },
  ctaLabel: {
    type: ControlType.String,
    title: 'CTA Label',
    defaultValue: 'Learn more',
    hidden: (props) => !props.showCta,
  },
  backImage: {
    type: ControlType.ResponsiveImage,
    title: 'Back Photo',
  },
  backImageFocal: {
    type: ControlType.Object,
    title: 'Back Photo Position',
    controls: imageFocalControls,
    hidden: (props) => !props.backImage,
  },
  backImageZoom: {
    type: ControlType.Number,
    title: 'Back Photo Zoom',
    defaultValue: 1,
    min: 0.5,
    max: 2,
    step: 0.05,
    hidden: (props) => !props.backImage,
  },
  profileImage: {
    type: ControlType.ResponsiveImage,
    title: 'Profile Photo',
  },
  showOnlineStatus: {
    type: ControlType.Boolean,
    title: 'Online Status',
    defaultValue: false,
  },
  onlineIndicatorColor: {
    type: ControlType.Color,
    title: 'Status Color',
    defaultValue: '#22c55e',
    hidden: (props) => !props.showOnlineStatus,
  },
  backColor: {
    type: ControlType.Color,
    title: 'Back Background',
    defaultValue: '#ffffff',
  },
  textColor: {
    type: ControlType.Color,
    title: 'Back Text',
    defaultValue: '#111827',
  },
  ctaColor: {
    type: ControlType.Color,
    title: 'Button Color',
    defaultValue: '#111827',
  },
  ctaTextColor: {
    type: ControlType.Color,
    title: 'Button Text',
    defaultValue: '#ffffff',
  },
  frontPanelColor: {
    type: ControlType.Color,
    title: 'Panel Background',
    defaultValue: '#ffffff',
    hidden: (props) => !props.showLabel,
  },
  frontTitleColor: {
    type: ControlType.Color,
    title: 'Title Color',
    defaultValue: '#111827',
    hidden: (props) => !props.showLabel,
  },
  frontDescriptionColor: {
    type: ControlType.Color,
    title: 'Description Color',
    defaultValue: '#6b7280',
    hidden: (props) => !props.showLabel,
  },
  labelPanelScale: {
    type: ControlType.Number,
    title: 'Panel Scale',
    defaultValue: 0.5,
    min: 0.25,
    max: 1,
    step: 0.05,
    displayStepper: true,
    hidden: (props) => !props.showLabel,
  },
  labelTextOffset: {
    type: ControlType.Object,
    title: 'Text Position',
    controls: labelTextOffsetControls,
    hidden: (props) => !props.showLabel,
  },
  labelPanelExtraWidth: {
    type: ControlType.Number,
    title: 'Panel Width',
    defaultValue: 0,
    min: 0,
    max: 120,
    step: 4,
    unit: 'px',
    displayStepper: true,
    hidden: (props) => !props.showLabel,
  },
  labelPanelPadding: {
    type: ControlType.Number,
    title: 'Panel Padding',
    defaultValue: 24,
    min: 0,
    max: 64,
    unit: 'px',
    hidden: (props) => !props.showLabel,
  },
  borderRadius: {
    type: ControlType.Number,
    title: 'Corner Radius',
    defaultValue: 40,
    min: 0,
    max: 80,
    unit: 'px',
  },
  panelScoopRadius: {
    type: ControlType.Number,
    title: 'Corner Curve',
    defaultValue: 35,
    min: 0,
    max: 60,
    unit: 'px',
    hidden: (props) => !props.showLabel,
  },
  padding: {
    type: ControlType.Number,
    title: 'Padding',
    defaultValue: 24,
    min: 0,
    max: 64,
    unit: 'px',
  },
  shadow: {
    type: ControlType.Boolean,
    title: 'Shadow',
    defaultValue: true,
  },
  revealMode: {
    type: ControlType.Enum,
    title: 'Reveal On',
    options: ['hover', 'click', 'tap', 'scroll'],
    optionTitles: ['Hover', 'Click', 'Tap', 'Scroll'],
    defaultValue: 'hover',
  },
  flipDirection: {
    type: ControlType.Enum,
    title: 'Flip Direction',
    options: ['horizontal', 'vertical'],
    optionTitles: ['Horizontal', 'Vertical'],
    defaultValue: 'horizontal',
  },
  animationStyle: {
    type: ControlType.Enum,
    title: 'Animation Style',
    options: ['smooth', 'snappy', 'dramatic'],
    optionTitles: ['Smooth', 'Snappy', 'Dramatic'],
    defaultValue: 'smooth',
  },
  mobileBehavior: {
    type: ControlType.Enum,
    title: 'Mobile Behavior',
    options: ['tap', 'scroll', 'disabled'],
    optionTitles: ['Tap', 'Scroll', 'Disabled'],
    defaultValue: 'tap',
  },
  autoFlip: {
    type: ControlType.Boolean,
    title: 'Auto Flip',
    defaultValue: false,
  },
  autoFlipDelay: {
    type: ControlType.Number,
    title: 'Auto Flip Delay',
    defaultValue: 3000,
    min: 500,
    max: 10000,
    unit: 'ms',
    hidden: (props) => !props.autoFlip,
  },
  threshold: {
    type: ControlType.Number,
    title: 'Scroll Threshold',
    defaultValue: 0.3,
    min: 0,
    max: 1,
    step: 0.05,
    hidden: (props) => props.revealMode !== 'scroll',
  },
  once: {
    type: ControlType.Boolean,
    title: 'Scroll Once',
    defaultValue: true,
    hidden: (props) => props.revealMode !== 'scroll',
  },
  staggerIndex: {
    type: ControlType.Number,
    title: 'Stagger Index',
    defaultValue: 0,
    min: 0,
    max: 20,
    displayStepper: true,
    hidden: (props) => props.revealMode !== 'scroll',
  },
});
